### ISSUE TITLE
Permission denied with ksmbd-tools 3.5.0-1, but works fine with 3.4.9-1.

### ISSUE THREAD

**Issue by bacon-cheeseburger** [namjaejeon/ksmbd-tools#197]
Hi,
I have a strange problem happening. Running ksmbd on two Debian Sid Linux systems, both running identical kernels (6.5.10), packages, ksmbd settings, and permission settings on shared dirs. System 1 works fine with ksmbd-tool 3.5.0. I can create/write directories/files no problem. On system 2 I get "permission denied". The only difference between the systems is system 1 has all local storage drives while system 2 (the one giving me "permission denied") has local storage and a usb drive being shared.

Broken system 2 example:

/storage/nvme/ksmbd.share  (this is the local storage root/parent ksmbd share)
/storage/nvme/ksmbd.share/dir1  (shared local dir)
/storage/nvme/ksmbd.share/dir2  (shared dir bind mounted from /dev/sdb1 usb drive)

Also, it doesn't matter if the client is Linux or Windows. If I downgrade back to ksmbd-tools 3.4.9-1, then system 2 works fine. I can do a git bisect if necessary..?

**Comment by atheik** [comment]
@bacon-cheeseburger,

Could you share your `ksmbd.conf` here? I would like to reproduce this.
Also, could you try giving `-v` as an option to `ksmbd.mountd`  and check what `DEBUG: ` messages appear in syslog?

**Comment by atheik** [comment]
@bacon-cheeseburger,

> ksmbd.conf
> ----8<-----

`writeable` and `writable` are two distinct share parameters that control the same thing. The `ksmbdshare` share inherits `writeable = no` from `global` but also sets its own `writable = yes` which is in conflict. The order they take effect is non-descript and whichever one is the latter cancels the former.

Please either change `writable = yes` to `writeable = yes` or remove `writable = yes` (`read only = no` already gives read-write access) in `ksmbdshare`. Then try to reproduce the error.

If you can still reproduce the error:

> syslog from broken 3.5.0-1 after reboot:
> ----8<-----
> syslog from working 3.4.9-1 after reboot:
> ----8<-----

In both these logs, `ksmbd.mountd -v` exits since `ksmbd.mountd` is already running, i.e. the PID in the `RUNSTATEDIR/ksmbd.lock` lock file is an existing process. Please first kill the existing `ksmbd.mountd` by stopping the service with `systemctl stop ksmbd`, then run `ksmbd.mountd -v` and trigger the "permission denied" error.

**Comment by bacon-cheeseburger** [comment]
@atheik 
Thank you for clarifying ksmbd.conf a bit. I left the global settings but changed the share definition by removing the `read only = no` and renaming `writable = yes` to `writeable = yes` so it's consistent with global. This seems to have fixed the problem and after double-checking the ksmbd.conf on the other system, I noticed it did not have that inconsistency, which explains why it worked fine.

So, false alarm due to conflicting config settings. Thank you for helping me get this sorted!

**Comment by atheik** [comment]
@bacon-cheeseburger,

Actually, this coupling between `read only` and `writeable` (and its aliases) seems to be a long-standing bug that needs to be addressed. On the 3.5.0 release there is however a related new bug. To work around it you *must* give `read only = no` in the `ksmbdshare` share to get read-write access consistently. Thank you very much for reporting this issue.

@namjaejeon,

Since share parameters are applied in the non-descript hash table iteration order, a share parameter should never undo the effect of an another. For example, `force user` checks `share->force_gid` such that it doesn't undo `force group` applied earlier. However, `read only` does not follow this convention since it may undo `writeable` (and so may its aliases). Since the hash table iteration order is non-descript, this means that a share with `read only = yes` and `writeable = yes` may or may not allow read-write access. With the 3.5.0 release, due to the default global `read only = yes` added in commit 54d2a02, this effect is in play for all shares that give `writeable = yes` instead of `read only = no`. So, I unwittingly introduced this new bug by not taking into account the non-descript hash iteration order.

Here's one way to fix this new bug:
<details>
<summary>[PATCH] ksmbd-tools: don't set `read only = yes' by default (click the arrow to expand)</summary>

````diff
From 6b643059b795c11ca9ac30e4e0a4d516b20c213b Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Atte=20Heikkil=C3=A4?= <atteh.mailbox@gmail.com>
Date: Tue, 7 Nov 2023 03:36:54 +0200
Subject: [PATCH] ksmbd-tools: don't set `read only = yes' by default
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Since share parameters are applied in the non-descript hash table
iteration order, a share parameter should never undo the effect of an
another. For example, `force user' checks `share->force_gid' such that
it doesn't undo `force group' applied earlier. However, `read only'
does not follow this convention since it may undo `writeable' (and so
may its aliases). Since the hash table iteration order is non-descript,
this means that a share with `read only = yes' and `writeable = yes'
may or may not allow read-write access. With the 3.5.0 release, due to
the default global `read only = yes' added in commit 54d2a02, this
effect is always in play for shares that give `writeable = yes' (or
its aliases) instead of `read only = no'. Fix this by not giving
`read only = yes' by default in the global section.

Note that not setting `KSMBD_SHARE_FLAG_READONLY' for initial shares is
fine as it is only used to set `KSMBD_TREE_CONN_FLAG_READ_ONLY' which
itself is unused (and was broken until commit 3f88fbe).

Note also that if the IPC$ share is given `KSMBD_SHARE_CONF_WRITABLE',
e.g. through the global section or it being defined by the user, it is
always guarded by `KSMBD_SHARE_FLAG_PIPE'.

Signed-off-by: Atte Heikkilä <atteh.mailbox@gmail.com>
---
 ksmbd.conf.5.in          | 2 +-
 ksmbd.conf.example       | 2 +-
 tools/config_parser.c    | 1 -
 tools/management/share.c | 2 +-
 4 files changed, 3 insertions(+), 4 deletions(-)

diff --git a/ksmbd.conf.5.in b/ksmbd.conf.5.in
index 7fcd7b6..b74f41f 100644
--- a/ksmbd.conf.5.in
+++ b/ksmbd.conf.5.in
@@ -224,7 +224,7 @@ Default: \fBread list = \fR
 Users are allowed read-only access to the share.
 With \fBread only = no\fR, the effect is the same as with \fBwriteable = yes\fR.
 
-Default: \fBread only = yes\fR
+Default: \fBread only = ; yes\fR
 .TP
 \fBrestrict anonymous\fR (G)
 How to restrict connections to any share as the user given with \fBguest account\fR.
diff --git a/ksmbd.conf.example b/ksmbd.conf.example
index ce4779d..cf3c57d 100644
--- a/ksmbd.conf.example
+++ b/ksmbd.conf.example
@@ -49,7 +49,7 @@
 	oplocks = yes
 	path = 
 	read list = 
-	read only = yes
+	read only = ; yes
 	store dos attributes = yes
 	valid users = 
 	veto files = 
diff --git a/tools/config_parser.c b/tools/config_parser.c
index af144b9..2be1a16 100644
--- a/tools/config_parser.c
+++ b/tools/config_parser.c
@@ -564,7 +564,6 @@ static void add_group_ipc_share_conf(void)
 {
 	add_group_key_value("comment = IPC share");
 	add_group_key_value("guest ok = yes");
-	add_group_key_value("read only = yes");
 }
 
 static int finalize_smbconf_parser(void)
diff --git a/tools/management/share.c b/tools/management/share.c
index 3719f96..037c5be 100644
--- a/tools/management/share.c
+++ b/tools/management/share.c
@@ -73,7 +73,7 @@ const char *KSMBD_SHARE_DEFCONF[KSMBD_SHARE_CONF_MAX] = {
 	"",
 	"no",
 	"",
-	"yes",
+	"; yes",
 /*5*/	"yes",
 	"",
 	"",
-- 
2.42.0

````
</details>

Note that this doesn't fix the long-standing bug where `read only` may undo `writeable` (and so may its aliases).
So, if the user gives `read only = yes` in the global section and attempts to override it in a share by giving `writeable = yes`, or vice versa, them being applied in the correct order is up to chance.

**Comment by atheik** [comment]
@namjaejeon,

There should be a new release very soon that fixes this new bug. I apologize for the trouble.

**Comment by namjaejeon** [comment]
@atheik No problem:) I will release it tonight! I am always grateful for your works.

**Comment by bacon-cheeseburger** [comment]
@atheik 
I'd like to mention that as an end-user, this whole `read only`, `writeable`,`writable` is a bit confusing. Are all these aliases, overlapping, and X can override Y but Y can override X stuff really necessary? Maybe it's my ignorance but it feels unnecessarily complicated. I thought I understood the problem but now I'm not sure. In my case, I'd like `read only = yes` and/or (`writeable = no` or `writable = no`) to be the global default. Then I'd like to decide for each share whether writing is allowed. I thought setting `writeable = no` globally, and then `writeable = yes` per share is correct, but `read only = yes` is also required in the r/w shares too? Does it have to come before or after the share `writeable = yes`? I really hope there's a way to clean these settings up or simplify them so the logic is clear, obvious, and results in the expected outcome from regular users like me.

Thank you for quickly responding to this report btw!

**Comment by bacon-cheeseburger** [comment]
@atheik 

> The gist of this issue is this: `read only`, `writeable`, `writable`, and `write ok` control the same feature, so make sure that only one of them gets applied to a share. If you give one of these parameters in `global` (e.g. `writable = no`), override its effect by using the same parameter in a share (e.g. give `writable = yes` instead of `read only = no` or `write ok = yes`). The 3.5.0 release is broken and so you must give `read only = no` in a share if you want read-write access. I hope this cleared things up.

Thank you for going into detail. It helps (, more with each read through). Overall it's still confusing why it's necessary to have so many aliases all controlling the same thing, acting almost like a circular firing squad. I wonder why such design choices were made. Am I wrong to think some kind of (partial) re-design would best serve the issue, and ultimately the people who have to understand how to properly configure ksmbd? Sometimes explaining/maintaining something complex causes more pain than just simplifying it.

**Comment by atheik** [comment]
@namjaejeon,

Please don't apply the patch yet. I will look into some other ways to fix this first.

**Comment by atheik** [comment]
@namjaejeon,

I updated the commit message and ksmbd.conf(5) changes in the patch at https://github.com/namjaejeon/ksmbd-tools/issues/197#issuecomment-1797181803. This fixes the new bug but retains the long-standing `read only`/`writable`/`writeable`/`write ok` conflict bug. Before applying it and making a new release, would you please double-check my claims made at the end of the commit message. Thank you.

For the release notes, if you mention the patch commit title, then please also append this to avoid confusion:
```
Shares are still read-only by default.
```

**Comment by namjaejeon** [comment]
>> +	"; yes",

@atheik I didn't read all thread yet. At quick glance, I can not understand why you add "; yes" instead of "no".

**Comment by atheik** [comment]
@namjaejeon,

> I didn't read all thread yet. At quick glance, I can not understand why you add "; yes" instead of "no".

That would not fix the new bug. Additionally, that would make shares read-write by default since `read only = no` sets `KSMBD_SHARE_FLAG_WRITEABLE`. The thread explains the new bug and the long-standing bug, but here's a summary:

Consider this `ksmbd.conf`:
```
[MyShare]
        path = /home/tester/MyShare
        read only = yes
        writable = yes
```

Above, the `MyShare` share may be read-only or it may be read-write since [share parameters get applied in non-descript order](https://github.com/namjaejeon/ksmbd-tools/blob/f489e4c/lib/management/share.c#L608). This is due to `g_hash_table_foreach` (and `g_hash_table_iter_next`) not having a defined iteration order. This is the long-standing bug that has existed ever since `writeable`, `writable`, and `write ok` were added. (`force user` and `force group` do not have this problem, since the former does not undo the effect of the latter.)

Consider this `ksmbd.conf`:
```
[MyShare]
        path = /home/tester/MyShare
        write ok = no
        writable = yes
```

Above, the share may be read-only or it may be read-write. This is the exact same long-standing bug.

After commit f489e4c (global share parameters), consider this `ksmbd.conf`:
```
[global]
        read only = yes
[MyShare]
        path = /home/tester/MyShare
        writable = yes
```

Above, this is the exact same long-standing bug, but users are far more likely to run into it like this. The share inherits `read only = yes` from `global` but also has its own `writable = yes`. Both get applied and the share may be read-only or it may be read-write.

After commit 54d2a02, a share inherits a share parameter from [`KSMBD_SHARE_DEFCONF`](https://github.com/namjaejeon/ksmbd-tools/blob/54d2a02/tools/management/share.c#L63-L101) if neither the share nor the `global` section has it. So, a share inherits [`read only = yes` ](https://github.com/namjaejeon/ksmbd-tools/blob/54d2a02/tools/management/share.c#L74) from `KSMBD_SHARE_DEFCONF` if neither the share nor the `global` section has `read only = <value>`.

Then, consider this `ksmbd.conf`:
```
[MyShare]
        path = /home/tester/MyShare
        writable = yes
```

Above, `MyShare` will inherit `read only = yes` from `KSMBD_SHARE_DEFCONF`. `writable = yes` and `read only = yes` are both applied and the share may be read-only or it may be read-write. `MyShare` must have `read only = no` to get read-write consistently, since then `read only = yes` from `KSMBD_SHARE_DEFCONF` is not inherited. This is the new bug, which interacts with the long-standing bug.

The new bug is fixed by the patch in https://github.com/namjaejeon/ksmbd-tools/issues/197#issuecomment-1797181803 (I updated the commit message again). Please double-check the claims I made in the last two paragraphs of the commit message.

**Comment by namjaejeon** [comment]
@atheik Applied, Thanks! I will release 3.5.1 version tonight.
